### ISSUE TITLE
About openttd, novapolis and one old event with pyramide

### ISSUE THREAD

**Issue by iskazain** [TheDude-gh/NewGRFs#1]
Hi there. Sorry for connect like this (no other ways found).
Once you made event for novapolis with pyramide https://www.novapolis.net/data/PyramidCargo2014-cargoschema.png
Its most playable thing for me :-) in openttd
But, because that was some event the industry set with candies and etc. i dont really... like :-)
Is it any way to replace all industries in that grf with other industries (mashinery for example like firs)? It can be awesome thing.
If u get this message pls mail me on iskazain@yandex.ru

**Comment by TheDude-gh** [comment]
Yes, it would be possible, in theory. 
Once I get to upload all my NewGRFs to this github repository, you can make yourself any changes to your liking ;-)
